nordic_radar: "/lustre/storeB/users/opmir9231/anemoi-datasets/nordic-radar-2020-2025-1km-5m.zarr"
opera: "/lustre/storeB/users/opmir9231/anemoi-datasets/opera-2020-2025-2km-15m.zarr"
netatmo: "/lustre/storeB/users/opmir9231/anemoi-datasets/netatmo-2020-2025-5m.zarr"
msg_seviri: "/lustre/storeB/users/opmir9231/anemoi-datasets/msg-seviri-2020-2025-3km-15m-nordic.zarr"
graph: "/lustre/storeB/users/opmir9231/graph/"
# To load the graph from a file, you need to provide a path here like: /path/to/your/graph.pt
# Then for each dataset the graph /path/to/your/graph_{dataset_name}.pt will be loaded if it exists.
# If no such file exists, the graph will be created from the config.
truncation: null
truncation_inv: null
loss_matrices_path: null
warm_start: null
