defaults:
- data: downscaling
- dataloader: downscaling
- diagnostics: downscaling
- system: slurm
- graph: lam_downscaling
- model: graphtransformer_ens
- training: downscaling

config_validation: True


