defaults:
  - paths: ppi
  - files: ppi

# number of GPUs per node and number of nodes (for DDP)
accelerator: auto
num_tasks_per_node: ${oc.decode:${oc.env:SLURM_NTASKS_PER_NODE}}
num_gpus_per_node: ${oc.decode:${oc.env:SLURM_GPUS_PER_NODE}}
num_nodes: ${oc.decode:${oc.env:SLURM_NNODES}}
num_gpus_per_model: ${oc.decode:${oc.env:SLURM_GPUS_PER_NODE}}
